In [66]:
import numpy
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# Parte 1: Introducción

### Ejercicio 1
Generar un tensor llamado **x** cuyo contenido sea el siguiente:

![Imagen](./rfaKGUG.png)

In [67]:
x = tf.constant([
    [
        [0,2,4,6,8], [ 10,12,14,16,18],
        [20,22,24,26,28]
    ],
    [
        [30,32,34,46,38], [40,42,44,46,48],
        [50,52,54,56,58]
    ]
])

print(x)

tf.Tensor(
[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]]

 [[30 32 34 46 38]
  [40 42 44 46 48]
  [50 52 54 56 58]]], shape=(2, 3, 5), dtype=int32)


### Ejercicio 2
Realizar los cambios necesarios en los siguientes tensores para que sea posible multiplicar cada columna del tensor "X" por el vector "y".

In [68]:
X = tf.ones((2, 4, 5, 3))
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y_2 = tf.reshape(y, (1, 1, 5, 1))

result = X * y_2    
print(result)


tf.Tensor(
[[[[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]

  [[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]

  [[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]

  [[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]]


 [[[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]

  [[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]

  [[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]

  [[1. 1. 1.]
   [2. 2. 2.]
   [3. 3. 3.]
   [4. 4. 4.]
   [5. 5. 5.]]]], shape=(2, 4, 5, 3), dtype=float32)


### Ejercicio 3
Sobre Tensores, implemente las operaciones Suma, Producto Tensorial y Contraccion Tensorial. Para ello agregue las operaciones tensoriales que sean pertinentes

In [69]:
def tensor_sum(a, b):
    return a + b

def tensor_product(a, b):
    return tf.tensordot(a, b, 1)

def tensor_contraction(a, b):
    return tf.tensordot(a, b, 1)



### Ejercicio 4
Descargar y estudiar el dataset de IMDB de Keras (num_words = 10000)
Separar el dataset en conjuntos de train y test

In [70]:
from tensorflow.keras.datasets import imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

print(f'Train data shape: {train_data.shape}')
print(f'Train labels shape: {train_labels.shape}')
print(f'Test data shape: {test_data.shape}')
print(f'Test labels shape: {test_labels.shape}')


Train data shape: (25000,)
Train labels shape: (25000,)
Test data shape: (25000,)
Test labels shape: (25000,)


# Ejercicio 5
Dentro del conjunto de Test extraer el primer review positivo y el primer negativo. Hacer la codificacion back-to-text de cada uno de ellos

In [71]:
# Cargar el diccionario de palabras inverso (índice a palabra)
word_index = imdb.get_word_index()
reverse_word_index = {value: key for (key, value) in word_index.items()}

# Decodificar una reseña de secuencia a texto
def decode_review(sequence):
    return ' '.join([reverse_word_index.get(i - 3, '?') for i in sequence])

# Extraer el primer review positivo y negativo
first_positive_index = next(i for i, label in enumerate(test_labels) if label == 1)
first_negative_index = next(i for i, label in enumerate(test_labels) if label == 0)

first_positive_review = test_data[first_positive_index]
first_negative_review = test_data[first_negative_index]

# Decodificar los reviews a texto
positive_review_text = decode_review(first_positive_review)
negative_review_text = decode_review(first_negative_review)

print("First positive review (decoded):")
print(positive_review_text)

print("\nFirst negative review (decoded):")
print(negative_review_text)

First positive review (decoded):
? this film requires a lot of patience because it focuses on mood and character development the plot is very simple and many of the scenes take place on the same set in frances ? the sandy dennis character apartment but the film builds to a disturbing climax br br the characters create an atmosphere ? with sexual tension and psychological ? it's very interesting that robert altman directed this considering the style and structure of his other films still the trademark altman audio style is evident here and there i think what really makes this film work is the brilliant performance by sandy dennis it's definitely one of her darker characters but she plays it so perfectly and convincingly that it's scary michael burns does a good job as the mute young man regular altman player michael murphy has a small part the ? moody set fits the content of the story very well in short this movie is a powerful study of loneliness sexual ? and desperation be patient ? u

### Ejercicio 6
Sin hacer uso de las librerias de Keras, crear una red neuronal feed-forward fully_connected con la siguiente arquitectura: capa de entrada - 16 -16 - capa de salida.
(Programar todas las funciones necesarias)


In [72]:
# Code here

### Ejercicio 7
Tomar un lote random de 100 reviews en el conjunto de train y hacer forward por su red neuronal estimando el error para ese lote. Definir la funcion de error pertinente.

In [73]:
# Code here

### Ejercicio 8
Usando Keras defina la misma red neuronal anterior

In [74]:
# Definir el modelo secuencial
model = models.Sequential()

# Capa de entrada
# La capa de entrada se puede definir implícitamente en la primera capa oculta
# Si las entradas son secuencias de longitud variable, se define input_shape=(None,)
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))

# Primera capa oculta con 16 neuronas y activación ReLU
model.add(layers.Dense(16, activation='relu'))

# Segunda capa oculta con 16 neuronas y activación ReLU
model.add(layers.Dense(16, activation='relu'))

# Capa de salida con una neurona (usada para clasificación binaria)
model.add(layers.Dense(1, activation='sigmoid'))


### Ejercicio 9
Entrene el modelo definido usando un batchs de 512 elementos y 20 epoch. Recuerden generar los conjuntos de validacion y train.

In [75]:
# Code here

### Ejercicio 10
Plotear las curvas de **Training vs Validation Loss** con la loss por cada epochs
Plotear las curvas de **Training vs Validation Accuracy** con el accuracy por cada epochs

Haga un resumen con las conclusiones observadas en ambas graficas

In [76]:
# Code here